### ISSUE TITLE
Suggest Violentmonkey instead of Tampermonkey

### ISSUE THREAD

**Issue by Segfavlt** [saucettv/WorkingTwitchAdBlockers#2]
Violentmonkey [firefox](https://addons.mozilla.org/en-US/firefox/addon/violentmonkey/) [chrome](https://chrome.google.com/webstore/detail/violentmonkey/jinjaccalgkegednnccohejagnlnfdag) is an open source user script manager for browsers. 

[Tampermonkey](https://github.com/Tampermonkey/tampermonkey) is closed source as of 2.9 and should no longer be recommended since it cannot be trusted.

**Comment by saucettv** [comment]
Thank you for bringing this to my attention, I have updated the readme, https://github.com/saucettv/WorkingTwitchAdBlockers/commit/8b350ed834c1c7bd774678e50204885e541c2adf

Will close this now, thanks again.
